### ISSUE TITLE
NoMethodError on the concurrent? method in Heya when running on Render.com

### ISSUE THREAD

**Issue by leemcalilly** [honeybadger-io/heya#177]
I'm getting an error when trying to run `rails heya:scheduler` on Production when my host is [Render](https://render.com). I'm getting this error:

`NoMethodError: undefined method 'concurrent?' for nil:NilClass`

Here's a [full write-up of the issue](https://stackoverflow.com/questions/72873837/heya-email-gem-not-working-in-production-on-render-nomethoderror-undefined-met) with my code and error logs on Render.

Is this a bug with the gem or am I doing something wrong? I've been working with Render support for several days on this, and we're at a loss.

**Comment by joshuap** [comment]
Hi @leemcalilly, I think this could be a heya bug. It's definitely strange, though—I haven't heard of any similar reports.

[This](https://github.com/honeybadger-io/heya/blob/85d445917b13f89d2ead79be50df5b75d6e84213/lib/heya/campaigns/scheduler.rb#L42) is where `MembershipsForUpdate` lambda gets called, and [this](https://github.com/honeybadger-io/heya/blob/85d445917b13f89d2ead79be50df5b75d6e84213/lib/heya/campaigns/queries.rb#L17) is where the error is raising. As you can see, there is no guard on the `membership` query on line 16, which I think is because technically we shouldn't be calling that code unless we're certain the membership exists ([this](https://github.com/honeybadger-io/heya/blob/85d445917b13f89d2ead79be50df5b75d6e84213/lib/heya/campaigns/scheduler.rb#L21) is the entrypoint in the scheduler).

I can think of three reasons why it's not finding the membership on [line 16 of queries.rb](https://github.com/honeybadger-io/heya/blob/85d445917b13f89d2ead79be50df5b75d6e84213/lib/heya/campaigns/queries.rb#L16):

1. The user doesn't exist or is `nil`
2. `campaign.gid` is returning the wrong value
3. The `CampaignMembership` really doesn't exist, but that's weird because if the code reached that point, that means the membership *was* found and returned on [line 21 of scheduler.rb](https://github.com/honeybadger-io/heya/blob/85d445917b13f89d2ead79be50df5b75d6e84213/lib/heya/campaigns/scheduler.rb#L21).

Could you open a production console session on Render and try stepping through the scheduler logic? You could inspect the result(s) of `membership = Queries::MembershipsToProcess.call(user: nil).first`, `step = GlobalID::Locator.locate(membership.step_gid)`, `campaign = GlobalID::Locator.locate(membership.campaign_gid)`, and `Queries::MembershipsForUpdate.call(campaign, membership.user)`. You could also inspect `membership = CampaignMembership.where(user: membershipuser, campaign_gid: campaign.gid)` to see if the membership is found.

You mentioned that this error is only in production—have you tried running everything locally and confirmed that the scheduler is queueing up emails?

Also, does the error still happen if the memberships are not concurrent?

**Comment by leemcalilly** [comment]
Thanks @joshuap. Mystery solved. Here's what happened. Earlier in the process of setting up Heya I did not have `concurrent: true` on `WelcomeCampaign.add(self, concurrent: true)` and `EvergreenCampaign.add(self, concurrent: true)`, but I kept deleting and re-adding users to test. 

To fix this I just needed to collect `Heya::CampaignMembership.all` into a variable and then `destroy_all` on the production database to remove all of the Heya Campaign Memberships that were orphans. Then I signed up a new user and all of the campaigns were delivered as expected.

So I guess that's not really a bug, but I could see that happening to someone else. Now I'm wondering how it might be able to fail more gracefully? Or display a more descriptive error message in this scenario?

**Comment by joshuap** [comment]
Maybe I could do something like this, but for deleted users:

https://github.com/honeybadger-io/heya/blob/f8635c0fbcf62129f8a3f09670146daad26c402d/lib/heya/campaigns/scheduler.rb#L17

**Comment by leemcalilly** [comment]
> @leemcalilly I'm pretty sure that you just need to add those `has_many` associations w/ `dependent: :delete_all` to your `User` model so that memberships and receipts are cleaned up when a user is deleted, unless I'm missing something. I need to update the docs and/or find a way to do this automatically to avoid this bug in the future. There is also probably a more graceful way to handle this issue if there _is_ an orphaned membership in the system.

You’re right. That makes sense!
